version: "3.9"
    
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb 
    environment:
       MONGO_INITDB_ROOT_USERNAME: USER
       MONGO_INITDB_ROOT_PASSWORD: PASS

    ports:
        - "27017:27017"
    deploy:
        resources:
            limits:
                cpus: "1"
                memory: "500MB"
 
